export const SORTED_BY_PRICE = 'SORTED_BY_PRICE'
export const SORTED_BY_SIZE = 'SORTED_BY_SIZE'
export const SORTED_BY_TITLE = 'SORTED_BY_TITLE'

export const CHANGE_CURRENT_PAGE = 'CHANGE_CURRENT_PAGE'
export const INC_CURRENT_PAGE = 'INC_CURRENT_PAGE'
export const DEC_CURRENT_PAGE = 'DEC_CURRENT_PAGE'

export const FILTER_CHANGE = 'FILTER_CHANGE'